version: '3.7'
services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./api:/var/www/api

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./api:/var/www/api
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm